# Generated by Django 3.1.4 on 2020-12-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('minus', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=255)),
                ('img1', models.ImageField(upload_to='C:\\Users\\Gafi Irfandi\\OneDrive\\Documents\\Projects\\Haludulu\\haludulu\\media')),
                ('img2', models.ImageField(upload_to='C:\\Users\\Gafi Irfandi\\OneDrive\\Documents\\Projects\\Haludulu\\haludulu\\media')),
                ('img3', models.ImageField(upload_to='C:\\Users\\Gafi Irfandi\\OneDrive\\Documents\\Projects\\Haludulu\\haludulu\\media')),
                ('size_s_stock', models.IntegerField()),
                ('size_m_stock', models.IntegerField()),
                ('size_l_stock', models.IntegerField()),
                ('size_xl_stock', models.IntegerField()),
            ],
        ),
    ]
