# Generated by Django 3.1.4 on 2020-12-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_img',
            field=models.ImageField(default=None, upload_to='C:\\Users\\Gafi Irfandi\\OneDrive\\Documents\\Projects\\Haludulu\\haludulu\\media'),
            preserve_default=False,
        ),
    ]
