# Generated by Django 3.1.4 on 2020-12-31 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img3',
        ),
    ]
